# Site settings
title: Claire Reynaud
email: info@clairereynaud.net
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Claire. I have 4 iPhone apps on the App Store.
  I also work as a consultant for other businesses.
  I craft apps that take advantage of the cloud.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.clairereynaud.net" # the base hostname & protocol for your site
twitter_username: ClaireReynaud
github_username:  creynaud

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      lang: en
  -
    scope:
      path: fr
    values:
      lang: fr
